version: 2
project_name: mysql-replica-healthcheck-agent
builds:
  - id: "mysql-replica-healthcheck-agent"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}
    binary: mysql-replica-healthcheck-agent
nfpms:
  - id: mysql-replica-healthcheck-agent
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    maintainer: rnakamine <rnakamine8080@gmail.com>
    builds:
      - mysql-replica-healthcheck-agent
    description: MySQL replica Healthcheck Agent
    formats:
      - deb
      - rpm
    contents:
      - src: package/mysql-replica-healthcheck-agent.service
        dst: /etc/systemd/system/mysql-replica-healthcheck-agent.service
        type: config
      - dst: /etc/mysql-replica-healthcheck-agent
        type: dir
        file_info:
          mode: 0700
      - src: example/replicas.yml
        dst: /etc/mysql-replica-healthcheck-agent/replicas.yml
        type: config
    license: Apache-2.0
